name: Deploy to Tailscale Server

on:
  push:
    branches:
      - main
    paths:
      - "dotfiles/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and Stow Dotfiles
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TAILSCALE_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/Homelab || exit 1
            git pull origin main

            # Stow dotfiles
            cd dotfiles || exit 1
            stow --restow */

            echo "Dotfiles deployed and stowed successfully"
